name: Update SS Configs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run config fetcher
      run: |
        python fetch_configs.py
      continue-on-error: false
    
    - name: Check if configs.txt exists
      run: |
        if [ ! -f configs.txt ]; then
          echo "configs.txt was not created!"
          exit 1
        fi
    
    - name: Commit and push if changes
      run: |
        git add configs.txt
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update configs [skip ci]"
          git push
        fi
